sudo: false
language: ruby

script: bundle exec ruby spec/unicode_blocks_spec.rb

rvm:
- 2.3.0
- 2.2
- 2.1
- ruby-head
- rbx-2
- jruby-head
- jruby-9.0.5.0

cache:
- bundler

matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
